import * as debug from './debug'
import * as UI from 'solid-ui'
import { store } from 'solid-logic'
import './styles/localUtils.css'

const kb = store
const ns = UI.ns
let dom

export function setDom (d) {
  dom = d
}

// ---------- Accessible modal dialog helpers ----------
// This code was generated by Generative AI (Raptor mini in GitHub Copilot) based on the following prompt:
// Regarding accessibility, how should I replace alert()/confirm() with accessible modal dialogs?
// Let us implement the modals in the localUtils.

// alert()/confirm().  The implementation ensures focus trapping, keyboard
// support, and hides the rest of the page from screen readers while the
// dialog is visible.

let modalOverlay = null
let previousFocus = null

function ensureModalOverlay () {
  // if we previously created an overlay but it was removed from the document
  // (tests clear body), rebuild it.  Checking presence ensures our reference
  // doesn't point at a detached element.
  if (modalOverlay && document.body.contains(modalOverlay)) return modalOverlay
  // otherwise drop stale reference and create a new element
  modalOverlay = null
  // overlay container
  modalOverlay = dom.createElement('div')
  modalOverlay.id = 'contacts-modal'
  modalOverlay.className = 'focus-trap hidden'
  modalOverlay.setAttribute('role', 'presentation')

  modalOverlay.innerHTML = `
    <div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" aria-describedby="modal-desc">
      <h2 id="modal-title"></h2>
      <div id="modal-desc"></div>
      <div id="modal-buttons"></div>
    </div>
  `

  document.body.appendChild(modalOverlay)

  // keyboard handling (esc/tab)
  modalOverlay.addEventListener('keydown', e => {
    if (e.key === 'Escape') {
      e.stopPropagation()
      // simulate cancel if available
      const cancelBtn = modalOverlay.querySelector('button[data-cancel]')
      if (cancelBtn) cancelBtn.click()
      else closeModal(false)
    } else if (e.key === 'Tab') {
      // simple focus trap: cycle through focusable elements inside overlay
      const focusable = Array.from(modalOverlay.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')).filter(el => !el.hasAttribute('disabled'))
      if (focusable.length === 0) return
      const idx = focusable.indexOf(document.activeElement)
      if (e.shiftKey) {
        if (idx === 0) {
          focusable[focusable.length - 1].focus()
          e.preventDefault()
        }
      } else {
        if (idx === focusable.length - 1) {
          focusable[0].focus()
          e.preventDefault()
        }
      }
    }
  })

  return modalOverlay
}

function hideSiblings (hide) {
  const siblings = Array.from(document.body.children).filter(c => c !== modalOverlay)
  siblings.forEach(el => {
    if (hide) el.setAttribute('aria-hidden', 'true')
    else el.removeAttribute('aria-hidden')
  })
}

function openModal ({ title, message, buttons }) {
  const overlay = ensureModalOverlay()
  previousFocus = document.activeElement
  hideSiblings(true)
  overlay.classList.remove('hidden')

  overlay.querySelector('#modal-title').textContent = title || ''
  const descEl = overlay.querySelector('#modal-desc')
  if (typeof message === 'string') {
    descEl.textContent = message
  } else {
    // allow passing nodes
    descEl.innerHTML = ''
    descEl.appendChild(message)
  }

  const btnContainer = overlay.querySelector('#modal-buttons')
  btnContainer.innerHTML = ''

  return new Promise(resolve => {
    buttons.forEach(btn => {
      const b = dom.createElement('button')
      b.setAttribute('type', 'button')
      b.textContent = btn.label
      if (btn.primary) b.classList.add('btn-primary')
      if (btn.cancel) b.setAttribute('data-cancel', 'true')
      b.addEventListener('click', () => {
        closeModal(btn.value)
        resolve(btn.value)
      })
      btnContainer.appendChild(b)
    })
    // focus first button
    const first = btnContainer.querySelector('button')
    if (first) first.focus()
  })
}

function closeModal (result) {
  if (modalOverlay) {
    modalOverlay.classList.add('hidden')
    hideSiblings(false)
    if (previousFocus && previousFocus.focus) previousFocus.focus()
  }
}

/**
 * Show an alert-style modal that has a single OK button.
 * @param {string} message
 * @param {string} [title]
 * @returns {Promise<true>}
 */
export function alertDialog (message, title = 'Information') {
  return openModal({
    title,
    message,
    buttons: [{ label: 'OK', value: true, primary: true }]
  })
}

/**
 * Show a confirm-style modal returning a boolean.
 * @param {string} message
 * @param {string} [title]
 * @returns {Promise<boolean>}
 */
export function confirmDialog (message, title = 'Confirm') {
  return openModal({
    title,
    message,
    buttons: [
      { label: 'Cancel', value: false, cancel: true },
      { label: 'OK', value: true, primary: true }
    ]
  })
}

// ---------- end of modal helpers ----------

/**
 * Normalize group URIs to ensure consistent representation.
 * Groups should be referenced with fragment #this, e.g., ...Group/AnotherGroup.ttl#this
 * If a group URI ends with .ttl (without #this), add #this
 * @param {string} uri - The group URI to normalize
 * @returns {string} The normalized group URI
 */
export function normalizeGroupUri (uri) {
  if (uri && uri.endsWith('.ttl')) {
    return uri + '#this'
  }
  return uri
}

export function complain (div, d, message) {
  div.appendChild(UI.widgets.errorMessageBlock(d, message, 'pink'))
}

export function getSameAs (kb, item, doc) {
  return kb.each(item, ns.owl('sameAs'), null, doc).concat(
    kb.each(null, ns.owl('sameAs'), item, doc))
}
//  For deleting an addressbook sub-folder eg person - use with care!
// @@ move to solid-logic
export function deleteRecursive (kb, folder) {
  return new Promise(function (resolve, reject) {
    kb.fetcher.load(folder).then(function () {
      const promises = kb.each(folder, ns.ldp('contains')).map(file => {
        if (kb.holds(file, ns.rdf('type'), ns.ldp('BasicContainer'))) {
          return deleteRecursive(kb, file)
        } else {
          debug.log('Recursive delete - we delete file ' + file.uri)
          return kb.fetcher.webOperation('DELETE', file.uri)
        }
      })
      debug.log('Recursive delete - we delete folder ' + folder.uri)
      promises.push(kb.fetcher.webOperation('DELETE', folder.uri))
      Promise.all(promises).then(_res => {
        resolve()
      }).catch(reject)
    }).catch(reject)
  })
}

// In a LDP work, deletes the whole document describing a thing
// plus patch out ALL mentiosn of it!    Use with care!
// beware of other data picked up from other places being smushed
// together and then deleted.
export async function deleteThingAndDoc (x) {
  const name = nameFor(x)
  if (!(await confirmDialog('Really DELETE ' + name + '?'))) {
    throw new Error('User cancelled contact deletion')
  }
  debug.log('deleteThingAndDoc - to be deleted ' + x)
  const ds = kb.statementsMatching(x).concat(kb.statementsMatching(undefined, undefined, x))
  try {
    await kb.updater.updateMany(ds)
    await kb.fetcher.delete(x.doc())
    debug.log('deleteThingAndDoc - deleted')
  } catch (err) {
    debug.error('Error deleting ' + x + '. Stack: ' + err)
    throw new Error('An error occured while deleting.')
  }
}

export function compareForSort (self, other) {
  let s = nameFor(self)
  let o = nameFor(other)
  if (s && o) {
    s = s.toLowerCase()
    o = o.toLowerCase()
    if (s > o) return 1
    if (s < o) return -1
  }
  if (self.uri > other.uri) return 1
  if (self.uri < other.uri) return -1
  return 0
}

// organization-name is a hack for Mac records with no FN which is mandatory.
export function nameFor (x) {
  const name =
    kb.any(x, ns.vcard('fn')) ||
    kb.any(x, ns.foaf('name')) ||
    kb.any(x, ns.vcard('organization-name'))
  return name ? name.value : '???'
}

/**
 * Prevent keyboard tabbing into labels/label-like links created by rdflib/solid-ui forms.
 * @param {HTMLElement} root
 */
export function skipLabelsFromTabbing (root) {
  // Many Solid-UI forms render field labels as focusable links (hrefs).
  // Make sure keyboard tabbing skips these label links entirely.
  const selectors = [
    'label',
    '.formFieldName a',
    '.classifierBox-label a',
    '.choiceBox-label a',
    '.label a',
    // Skip focusable label-like links created by Solid-UI forms, including the vcard note link
    'a[href="http://www.w3.org/2006/vcard/ns#note"]',
    'a[href$="#note"]',
  ].join(', ')

  // Some environments have NodeLists without forEach (e.g., older Safari).
  const nodes = root?.querySelectorAll?.(selectors)
  if (!nodes) return

  Array.from(nodes).forEach(el => {
    // Some browsers may return null for tabIndex, and some elements may not
    // expose tabIndex at all (e.g., SVG elements), so guard before setting.
    if (typeof el.tabIndex === 'number' && el.tabIndex !== -1) {
      el.tabIndex = -1
    }
    // Ensure those label links are not announced as focusable elements
    if (el.getAttribute('aria-hidden') !== 'true') {
      el.setAttribute('aria-hidden', 'true')
    }
  })
}

export function isAWebID (subject) {
  const t = kb.findTypeURIs(subject.doc())
  return !!t[ns.foaf('PersonalProfileDocument').uri]
}
