// This code was generated by raptor mini in GitHub Copilot.
import { beforeEach, describe, expect, test } from 'vitest'
import { axe } from 'vitest-axe'
import { alertDialog, setDom } from '../../src/localUtils'

describe('modal accessibility', () => {
  beforeEach(() => {
    document.body.innerHTML = ''
    setDom(document)
  })

  test('alertDialog is accessible according to axe', async () => {
    alertDialog('Hi!').then(() => {})
    await Promise.resolve()

    const axeResults = await axe(document.body)
    expect(axeResults.violations).toHaveLength(0)
  })
})
