// This code was generated by raptor mini in GitHub Copilot.
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { axe } from 'vitest-axe'
import * as UI from 'solid-ui'
import { authn, store } from 'solid-logic'
import pane from '../../src/contactsPane'
import { sym, parse } from 'rdflib'
import { context, doc, prefixes, web } from './setup'

// ensure the store knows this is an AddressBook so asyncRender will build UI

const base = doc.dir()?.uri || ''
const book = sym(base + 'book.ttl#this')
const group = sym(base + 'group.ttl#this')
const person = sym(base + 'group.ttl#person')
const webMap = web as Record<string, string>
const originalByName = context.session.paneRegistry.byName
const contactPaneRenderMock = vi.fn(() => {
  const paneDiv = document.createElement('div')
  paneDiv.textContent = 'mock contact pane'
  return paneDiv
})

webMap[base + 'book.ttl'] = `
<#this> a vcard:AddressBook;
    vcard:fn "Test address book".
`
webMap[base + 'group.ttl'] = `
<#this> a vcard:Group;
    vcard:fn "Selected group";
    vcard:hasMember <#person>.

<#person> a vcard:Individual;
    vcard:fn "Selected person".
`
for (const uri in webMap) {
  parse(prefixes + webMap[uri], store, uri)
}

beforeEach(() => {
  document.body.innerHTML = ''
  vi.restoreAllMocks()
  contactPaneRenderMock.mockClear()
  context.session.paneRegistry.byName = (name: string) => {
    if (name === 'contact') {
      return { render: contactPaneRenderMock }
    }
    return originalByName(name)
  }
})

describe('contacts-pane accessibility', () => {
  it('renders an empty UI of an address book', async () => {
    const div = pane.render(book, context)
    expect(div.classList.contains('contactPane')).toBe(true)
    expect(div.innerHTML).toMatch('')
    expect(div.dataset.paneWidth).toBeDefined()
    expect(div.dataset.paneNarrow).toBeDefined()
    expect(div.dataset.viewportNarrow).toBeDefined()
    // check accessibility of the generated DOM (ignore aria-allowed-role for now)
    const axeResults = await axe(div, { rules: { 'aria-allowed-role': { enabled: false } } })
    expect(axeResults.violations).toHaveLength(0)
  })

  it('opens the add-contact dialog and updates the pane when it closes with a person', async () => {
    const webId = 'https://janedoe.example/profile/card#me'
    vi.spyOn(authn, 'currentUser').mockReturnValue(webId as any)
    vi.spyOn(authn, 'checkUser').mockResolvedValue(webId as any)

    let dialogConfig: any
    const showDialogSpy = vi.spyOn(UI, 'showDialog').mockImplementation((DialogComponent, config) => {
      expect((DialogComponent as { name?: string }).name).toBe('AddContactModal')
      dialogConfig = config
      return document.createElement('div') as any
    })

    const div = pane.render(book, context)
    await new Promise(resolve => setTimeout(resolve, 0))

    const newContactButton = (Array.from(div.querySelectorAll('button')) as HTMLButtonElement[])
      .find((button) => button.textContent?.includes('New contact'))
    expect(newContactButton).toBeTruthy()

    newContactButton?.click()

    expect(showDialogSpy).toHaveBeenCalledTimes(1)
    expect(dialogConfig?.props).toEqual({
      book,
      selectedGroups: {}
    })

    dialogConfig.props.selectedGroups[group.uri] = true
    dialogConfig.onClose(person)

    expect(contactPaneRenderMock).toHaveBeenCalledWith(person, context)
    expect(div.querySelector('.detailsSectionContent--wide')).toBeTruthy()
    expect(div.querySelector('.detailsSectionContent')?.textContent).toContain('mock contact pane')
    expect(div.querySelector('.personLi.selected')?.textContent).toContain('Selected person')
  })

  it('includes a clear button in the search input and it works', async () => {
    const div = pane.render(book, context)
    // let asyncRender finish (it runs in a microtask)
    await new Promise(resolve => setTimeout(resolve, 0))
    const input = div.querySelector('.searchInput') as HTMLInputElement
    expect(input).toBeTruthy()
    const clear = div.querySelector('.searchClearButton') as HTMLElement
    expect(clear).toBeTruthy()
    // initially hidden via utility class
    expect(clear.classList.contains('hidden')).toBe(true)
    // simulate typing
    input.value = 'hello'
    input.dispatchEvent(new Event('input'))
    expect(clear.classList.contains('hidden')).toBe(false)
    // clicking clear should reset input and hide button again
    clear.click()
    expect(input.value).toBe('')
    expect(clear.classList.contains('hidden')).toBe(true)
    // run axe check on the full pane container after interactivity
    const axeResults = await axe(div, { rules: { 'aria-allowed-role': { enabled: false } } })
    expect(axeResults.violations).toHaveLength(0)
  })
})
